name = "DMRJtensor"
uuid = "5b179a51-5399-4802-8f6e-f7014fc12e6f"
authors = ["Thomas E. Baker"]
version = "0.9.4"

[compat]
julia = "1.8.2"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
